version: "3"
services:
  php-nodejs:
    build: .
    container_name: php-nodejs
    image: docker-php
    tty: true
    ports:
      - 3000:3000 # for browsersync
      - 3001:3001 # for browsersync ui
    environment:
      PHP_IDE_CONFIG: serverName=xdebug-docker
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      XDEBUG_SESSION: ${XDEBUG_SESSION}
      TZ: ${TZ:-UTC}
    volumes:
      - ./apps:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./apps:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

  mysql:
    image: "mysql:8.0"
    container_name: mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
    volumes:
      - "app-mysql:/var/lib/mysql"
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - "app-redis:/data"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-mysql:
    driver: local
  app-redis:
    driver: local
