#!/bin/sh

echo "Checking projects dependencies..."
for folder in /var/www/*/; do
    echo "Folder: $folder"

    if [ -f "$folder/composer.json" ]; then
        if [ -d "$folder/vendor" ]; then
            if [ $(ls -A $folder/vendor | wc -l) -ne 0 ]; then
                echo "The dependencies have already been installed"
                continue
            fi
        fi
        composer install -d "$folder"
    else
        echo "This is not a project managed by composer. Skipping ..."
    fi

    if [ -f "$folder/package.json" ]; then
        if [ -d "$folder/node_modules" ]; then
            if [ $(ls -A $folder/node_modules | wc -l) -ne 0 ]; then
                echo "The dependencies have already been installed"
                continue
            fi
        fi
        npm i --prefix "$folder"
        npm audit fix --prefix "$folder"
    else
        echo "This is not a project managed by npm. Skipping ..."
    fi
done

# Xdebug does not work using service instead of init.d
/etc/init.d/php7.4-fpm start

bash
